config/routes.rb
Rails.application.routes.draw do
  resources :waters
  resources :coffees
  resources :meetings
  resources :events
  resources :posts
  root to: 'posts#index'
  get "/pages/*page" => "pages#show"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coffee.rb
class Coffee < ApplicationRecord
    belongs_to :user
    #time zones
    #config.time_zone = 'Amsterdam'
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: [:show, :edit, :update, :destroy]

  # GET /coffees
  # GET /coffees.json
  def index
    @coffees = Coffee.all
  end

  # GET /coffees/1
  # GET /coffees/1.json
  def show
  end

  # GET /coffees/new
  def new
    @coffee = Coffee.new(coffee_params)
  end

  # GET /coffees/1/edit
  def edit
  end

  # POST /coffees
  # POST /coffees.json
  def create
    @coffee = Coffee.new(coffee_params)

    respond_to do |format|
      if @coffee.save
        format.html { redirect_to @coffee, notice: 'Coffee was successfully created.' }
        format.json { render :show, status: :created, location: @coffee }
      else
        format.html { render :new }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffees/1
  # PATCH/PUT /coffees/1.json
  def update
    respond_to do |format|
      if @coffee.update(coffee_params)
        format.html { redirect_to @coffee, notice: 'Coffee was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffee }
      else
        format.html { render :edit }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffees/1
  # DELETE /coffees/1.json
  def destroy
    @coffee.destroy
    respond_to do |format|
      format.html { redirect_to coffees_url, notice: 'Coffee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee
      @coffee = Coffee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_params
      params.require(:coffee).permit(:measurement_type, :quantity, :user_id)
    end
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/views/coffees/_form.html.erb
<%= form_with(model: coffee, local: true) do |form| %>
  <% if coffee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

      <ul>
        <% coffee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <p><b>Measurement Type:</b> Cup</p>
    <%= form.hidden_field :measurement_type, value: 1 %>
  </div>

  <div class="field">
    <p><b>Quantity:</b> 1</p>
    <%= form.hidden_field :quantity, value: 1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<h1>Editing Coffee</h1>

<%= render 'form', coffee: @coffee %>

<%= link_to 'Show', @coffee %> |
<%= link_to 'Back', coffees_path %>

app/views/coffees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffees</h1>

<table>
  <thead>
    <tr>
      <th>Measurement type</th>
      <th>Quantity</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffees.each do |coffee| %>
      <tr>
        <td>
            <%if coffee.measurement_type ==1 %>
                Cup
            <% elsif coffee.measurement_type == 2 %>
                ml
            <% end %>
        </td>
        <td><%= coffee.quantity %></td>
        <td><%= coffee.user.username %></td>
        <td><%= link_to 'Show', coffee %></td>
        <td><%= link_to 'Edit', edit_coffee_path(coffee) %></td>
        <td><%= link_to 'Destroy', coffee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee', new_coffee_path %>

app/views/coffees/new.html.erb
<h1>New Coffee entry</h1>

<%= render 'form', coffee: @coffee %>

<%= link_to 'Back', "/pages/userinfo" %>

app/views/coffees/show.html.erb
<p>
  <strong>Measurement type:</strong>
    <%if @coffee.measurement_type ==1 %>
            Cup
    <% elsif @coffee.measurement_type == 2 %>
            ml
    <% end %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @coffee.quantity %>
</p>

<%= link_to 'Back', "/pages/userinfo" %>