config/routes.rb
Rails.application.routes.draw do
  resources :waters
  resources :coffees
  resources :meetings
  resources :events
  resources :posts
  root to: 'posts#index'
  get "/pages/*page" => "pages#show"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
    belongs_to :user
    #time zones
    #config.time_zone = 'Amsterdam'
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:show, :index]
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
      @meeting = Meeting.new(meeting_params)
      #previously used for activity type refining, now done through select tag
      #if (@meeting[:activitytype] == 1)
          #@meeting[:name] = "RUN"
      #end

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :activitytype, :start_time, :end_time, :user_id)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="field">
    <%= form.label :activitytype %>
    <%= form.select :activitytype ,  [['WALK',1],['COMMUTE',2]] %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %>
<% if current_user && current_user.admin %>
    |<%= link_to 'Back', meetings_path %>
<% end %>

app/views/meetings/index.html.erb
    <% if current_user && current_user.admin %>
    <p id="notice"><%= notice %></p>
    <h1>Meetings</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th>Start time</th>
          <th>End time</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
          <% if current_user && current_user.admin %>
              <% @meetings.each do |meeting| %>
                  <tr>
                    <td><%= meeting.name %></td>
                    <td><%= meeting.activitytype %></td>
                    <td><%= meeting.start_time.day %>/<%= meeting.start_time.month %>/<%= meeting.start_time.year %></td>
                    <td><%= meeting.end_time.day %>/<%= meeting.end_time.month %>/<%= meeting.end_time.year %></td>
                      <td><%= meeting.user_id %></td>
                    <td><%= link_to 'Show', meeting %></td>
                      <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
                        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
          <% else%>
             <% current_user.meetings.each do |meeting| %>
                  <tr>
                    <td><%= meeting.name %></td>
                    <td><%= meeting.activitytype %></td>
                    <td><%= meeting.start_time.day %>/<%= meeting.start_time.month %>/<%= meeting.start_time.year %></td>
                    <td><%= meeting.end_time.day %>/<%= meeting.end_time.month %>/<%= meeting.end_time.year %></td>
                    <td><%= meeting.user.username %></td>
                    <td><%= link_to 'Show', meeting %></td>
                        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
          <% end%>

      </tbody>
    </table>

    <br>

    <%= link_to 'New Meeting', new_meeting_path %>
<% else %>
    <div class="row justify-content-center" style="margin-top: 10%; ">
        <p class="h4">You dont have access. Sorry !</p>
    </div>
<% end %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @meeting.activitytype %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<p>
    <strong>User name:</strong>
    <%= @meeting.user.username %>
    <br>
    <strong>User email:</strong>
    <%= @meeting.user.email %>
    <br>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %>
<% if current_user && current_user.admin %>
    |<%= link_to 'Back', meetings_path %>
<% end %>