config/routes.rb
Rails.application.routes.draw do
  resources :waters
  resources :coffees
  resources :meetings
  resources :events
  resources :posts
  root to: 'posts#index'
  get "/pages/*page" => "pages#show"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/water.rb
class Water < ApplicationRecord
    belongs_to :user
    #time zones
    #config.time_zone = 'Amsterdam'
end

app/controllers/waters_controller.rb
class WatersController < ApplicationController
  before_action :set_water, only: [:show, :edit, :update, :destroy]

  # GET /waters
  # GET /waters.json
  def index
    @waters = Water.all
  end

  # GET /waters/1
  # GET /waters/1.json
  def show
  end

  # GET /waters/new
  def new
    @water = Water.new(water_params)
  end

  # GET /waters/1/edit
  def edit
  end

  # POST /waters
  # POST /waters.json
  def create
    @water = Water.new(water_params)

    respond_to do |format|
      if @water.save
        format.html { redirect_to @water, notice: 'Water was successfully created.' }
        format.json { render :show, status: :created, location: @water }
      else
        format.html { render :new }
        format.json { render json: @water.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waters/1
  # PATCH/PUT /waters/1.json
  def update
    respond_to do |format|
      if @water.update(water_params)
        format.html { redirect_to @water, notice: 'Water was successfully updated.' }
        format.json { render :show, status: :ok, location: @water }
      else
        format.html { render :edit }
        format.json { render json: @water.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waters/1
  # DELETE /waters/1.json
  def destroy
    @water.destroy
    respond_to do |format|
      format.html { redirect_to waters_url, notice: 'Water was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water
      @water = Water.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def water_params
      params.require(:water).permit(:measurement_type, :quantity, :user_id)
    end
end

app/helpers/waters_helper.rb
module WatersHelper
end

app/views/waters/_form.html.erb
<%= form_with(model: water, local: true) do |form| %>
  <% if water.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(water.errors.count, "error") %> prohibited this water from being saved:</h2>

      <ul>
        <% water.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <p><b>Measurement Type:</b> Cup</p>
    <%= form.hidden_field :measurement_type, value: 1 %>
  </div>

  <div class="field">
    <p><b>Quantity:</b> 1</p>
    <%= form.hidden_field :quantity, value: 1 %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waters/edit.html.erb
<h1>Editing Water</h1>

<%= render 'form', water: @water %>

<%= link_to 'Show', @water %> |
<%= link_to 'Back', waters_path %>

app/views/waters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waters</h1>

<table>
  <thead>
    <tr>
      <th>Measurement type</th>
      <th>Quantity</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waters.each do |water| %>
      <tr>
        <td>
            <%if water.measurement_type ==1 %>
                Cup
            <% elsif water.measurement_type == 2 %>
                ml
            <% end %>
        </td>
        <td><%= water.quantity %></td>
        <td><%= current_user.username %></td>
        <td><%= link_to 'Show', water %></td>
        <td><%= link_to 'Edit', edit_water_path(water) %></td>
        <td><%= link_to 'Destroy', water, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Water', new_water_path %>

app/views/waters/new.html.erb
<h1>New Water entry</h1>

<%= render 'form', water: @water %>

<%= link_to 'Back', "/pages/userinfo" %>

app/views/waters/show.html.erb
<p>
  <strong>Measurement type:</strong>
  <%if @water.measurement_type ==1 %>
            Cup
    <% elsif @water.measurement_type == 2 %>
            ml
    <% end %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @water.quantity %>
</p>


<%= link_to 'Back', "/pages/userinfo" %>