config/routes.rb
Rails.application.routes.draw do
  resources :waters
  resources :coffees
  resources :meetings
  resources :events
  resources :posts
  root to: 'posts#index'
  get "/pages/*page" => "pages#show"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<!-- main content Section -->

        <% if current_user %>
            <div class="row justify-content-center" style="margin-top: 50px;">
                <div class="profile-userbuttons">
                    <button type="button" class="btn btn-info btn-lg"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></button>
                </div>
            </div>
        <% else %>
              <div style="margin-top: 20px;margin-bottom: 20px;">
                    <div class="row justify-content-center">
                    <div class="profile-userbuttons" style="margin-right: 20px;">
                        <a href="<%= new_user_registration_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN UP </button></a>
                    </div>
                    <div class="profile-userbuttons">
                        <a href="<%= new_user_session_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN IN </button></a>
                    </div>
                    </div>
                </div>
        <% end %>
        <br>
        <div class="row justify-content-center">
            <div class="profile-userbuttons">
                <a href="<%= posts_path %>"><button type="button" class="btn btn-info btn-lg"> POSTS </button></a>
            </div>
        </div>

app/views/pages/newentrypreface.html.erb
<div class="container">
<!-- logged in  with posts-->
<% if current_user %>
    <div class="column">

    <!-- info text -->
    <div class="ui middle aligned center aligned grid ">
        <div class="row">
            <div class="eleven wide column">
                <!--h1 class="ui header aligned left">New entry</h1-->
                <div class="ui divided items secondary segment">
                     <div class="item" style="text-align:left">
                        <div class="content">
                          <div class="header">Activity logging</div>
                          <div class="meta">
                              <p>Through this feature of the platform you can log your activites in the form of posts. Every activity has a title to fill in and a description to add comments, if you wish. Each activity also has a type to choose from and a timestamp.</p>
                          </div>
                          <div class="description">
                            <p></p>
                          </div>
                        </div>
                    </div>
                    <div class="item" style="text-align:left">
                        <div class="content">
                          <div class="header">Activity types</div>
                            <% if current_user && current_user.condition == 1%> 
                          <div class="meta">
                              <p> You are free to choose activity types from a group of low intensity physical activities. Those cover the whole spectrum of physical activity, from sport to commuting, gardening and even housework. The goal to perfom as many low intensity physical activities as you wish. In the <b>"PLANS"</b> section you can find a sample schedule for activity and we higly encourage you to follow it. It is formed under the guideline of the World Health Organisation for a healhty and active daily lifestyle. </p>
                          </div>
                            <% else %>
                          <div class="meta">
                              <p> You are free to choose activity types from the following three low intensity physical activities. Walking and commuting (cycling or else) are good examples of everyday low intensity exercise. If those do not cover your preferences, you can choose <b>"Other"</b>as activity type and type in the description more details of what you did. The goal to perfom as many low intensity physical activities as you wish. In the <b>"PLANS"</b> section you can find a sample schedule for activity and we higly encourage you to follow it. It is formed under the guideline of the World Health Organisation for a healhty and active daily lifestyle. </p>
                          </div>
                            <% end %>
                          <div class="description">
                            <p></p>
                          </div>
                        </div>
                    </div>
                    <div class="item" style="text-align:left">
                        <div class="content">
                          <div class="header">Mood and entertainment</div>
                          <div class="meta">
                              <p>We want you to think and reflect on which extend you had fun during this activity and what was your mood during that activity. Please don not forget to fill in those two questions through the sliders !</p>
                          </div>
                          <div class="description">
                            <p></p>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- info text -->

    <!-- button -->
        <div class="ui middle aligned center aligned grid ">
            <div class="row">
                <div class="eleven wide column">
                    <% if current_user && current_user.condition==1%>
                        <%= link_to "NEW ENTRY", new_post_path(:post => {:created_at => DateTime.now }), class: "ui secondary segment larger-text", style: 'width:100%'%>
                    <% else %>
                        <%= link_to "WALK", new_post_path(:post => {:created_at => DateTime.now, :entry_type => 1 }), class: "ui secondary segment larger-text", style: 'width:100%'%>
                        <%= link_to new_post_path(:post => {:created_at => DateTime.now, :entry_type => 2 }), class: "ui secondary segment larger-text", style: 'width:100%' do%> COMMUTE<%end%>
                        <%= link_to "OTHER", new_post_path(:post => {:created_at => DateTime.now, :entry_type => 3 }), class: "ui secondary segment larger-text", style: 'width:100%'%>
                    <% end %>

                </div>
            </div>
        </div>
    <!-- button -->
    </div>
    <% else %>
    <!-- not logged in view -->
        <div style="margin-top: 20px;margin-bottom: 20px; " class="not-logged">
            <div class="row justify-content-center">
                <div class="profile-userbuttons" style="margin-right: 20px;">
                    <a href="<%= new_user_registration_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN UP </button></a>
                </div>
                <div class="profile-userbuttons">
                    <a href="<%= new_user_session_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN IN </button></a>
                </div>
            </div>
        </div>
        <!-- not logged in view -->
    <% end %>
</div>

app/views/pages/plans.html.erb
<% if current_user %>
    <!-- Signed in view -->
    <div class="center">
        <%= week_calendar number_of_weeks: 2, events: current_user.meetings.all do |date, meetings| %>
            <%= date.strftime("%B") %> <%= date.day %>
            <% meetings.each do |meeting| %>
                <div>
                    <!-- commented out the filtering to check the populate_meetings func -->
                         <% if meeting.activitytype == 0 %>
                                <!-- passing params to new post !-->
                                <div class="event">
                                    <%= link_to meeting.name, new_post_path(:post => {:title => meeting.name, :created_at => meeting.start_time, :entry_type => meeting.activitytype }) %><i class="icon-chevron-right icon-position"></i>
                                </div>
                                <!-- autonomy condition -->
                                <% if current_user.condition == 1 %>
                                    <div class="btn ">
                                        <%= link_to "Edit", edit_meeting_path(meeting.id) %>
                                    </div>
                                <% end %>
                            <% end %>
                        <% if current_user.walkpref == 1 %>
                            <% if meeting.activitytype == 1 %>
                                <!-- passing params to new post !-->
                                <div class="event">
                                    <%= link_to meeting.name, new_post_path(:post => {:title => meeting.name, :created_at => meeting.start_time, :entry_type => meeting.activitytype }) %><i class="icon-chevron-right icon-position"></i>
                                </div>
                                <!-- autonomy condition -->
                                <% if current_user.condition == 1 %>
                                    <div class="btn ">
                                        <%= link_to "Edit", edit_meeting_path(meeting.id) %>
                                    </div>
                                <% end %>
                            <% end %>
                        <% end %>
                        <% if current_user.commutepref == 1 %>
                            <% if meeting.activitytype == 2 %>
                                <!-- passing params to new post !-->
                                <div class="event">
                                    <%= link_to meeting.name, new_post_path(:post => {:title => meeting.name, :created_at => meeting.start_time, :entry_type => meeting.activitytype }) %><i class="icon-chevron-right icon-position"></i>
                                </div>
                                <!-- autonomy condition -->
                                <% if current_user.condition == 1 %>
                                    <div class="btn ">
                                        <%= link_to "Edit", edit_meeting_path(meeting.id) %>
                                    </div>
                                <% end %>
                            <% end %>
                        <% end %>
                    <!-- end of filtering -->
                </div>
            <% end %>
        <% end %>
    </div>
    <!-- meetings button just for admin and test purposes-->
    <% if current_user && current_user.admin %>
    <div class="center">
        <div class="profile-userbuttons">
            <a href="<%= meetings_path %>"><button type="button" class="btn btn-success btn-lg"> Meetings </button></a>
        </div>
    </div>
    <% end %>
    <!-- meetings button end -->
<% else %>
        <!-- non signed in option -->
        <div style="margin-top: 20px;margin-bottom: 20px;">
             
            <div class="row justify-content-center">
                <div class="profile-userbuttons" style="margin-right: 20px;">
                    <a href="<%= new_user_registration_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN UP </button></a>
                </div>
                <div class="profile-userbuttons">
                    <a href="<%= new_user_session_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN IN </button></a>
                </div>
            </div>
        </div>
<% end %>

app/views/pages/userinfo.html.erb
<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->
<div class="container">
            <% if current_user %>
            <div class="ui two column grid segment">
                <div class="column">
                    <!-- SIDEBAR USER TITLE -->
                        <div class="row justify-content-center">
                            <div class="profile-usertitle">
                                <div class="h3" style="color : #339699">
                                    <%= current_user.username %>
                                </div>
                            </div>
                        </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR BUTTONS -->
                    <div class="row justify-content-center">
                    <div class="profile-userbuttons">
                        <div class="field">
                        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"ui negative medium button"%>
                        </div>
                        <div class="field">
                        <%= link_to "Edit user preferences", edit_user_registration_path, class:"ui small basic button"%>
                        </div>
                    </div>
                    </div>
                    <br>
                    <br>
                <% end %>
				<!-- END SIDEBAR BUTTONS -->
                <!-- USER water and coffee and add actions-->
                <% if current_user %>
                <div class="row justify-content-center">
                    <div class="col-md-auto">
                        <!-- <p class="h5">Water drank today:</p>
                        <br> -->
                        <!-- displays current weeks count, ped day-->
                        <p class="h5">Coffee drank today:
                            <%= current_user.coffees.select{|coffee| coffee.created_at.day == DateTime.now.day }.size %><b> / <%= current_user.climit %> cups </b>
                            <div class="profile-userbuttons">
                                <%= link_to "Add coffee" , new_coffee_path(:coffee =>{:measurement_type => '1', :quantity => '1', :user_id => current_user.id}), class: "ui basic button" %>
                            </div>
                        </p>
                        <!-- displays current weeks count, ped day-->
                        <p class="h5">Water drank today:
                            <%= current_user.waters.select{|water| water.created_at.day == DateTime.now.day }.size %><b> / <%= current_user.wlimit %> cups</b>
                            <div class="profile-userbuttons">
                                <%= link_to "Add water" , new_water_path(:water =>{:measurement_type => '1', :quantity => '1', :user_id => current_user.id}), class: "ui basic button" %>
                            </div>
                        </p>
                        <br>
                    </div>
                </div>
                <% end %>
                <!-- USER water and coffee END -->

                </div>
            </div>
                <!-- END SIDEBAR USERPIC -->

				<!-- FEEDBACK SECTION -->
                <div class="row justify-content-center">
                    <!--Div that will hold the pie chart-->
                    <div class="col-md-auto">
                        <!--chartkick scripts-->
                        <script src="https://www.gstatic.com/charts/loader.js"></script>
                        <script src="chartkick.js"></script>
                        <%= javascript_include_tag "//www.gstatic.com/charts/loader.js", "chartkick" %>
                        <% if current_user %>
                            <!-- chart affect for posts -->
                            <% if current_user && current_user.condition == 1 %>
                                <!-- option 1: ugly overlaid graph with library settings -->
                                <%#= line_chart [
                                  {name: "All users", data: Post.pluck("created_at, affect")},
                                  {name: "Your data", data: current_user.posts.pluck("created_at, affect")}
                                ], library:  lib_set_affect  %>
                                <br>
                                <!-- option 2: WORKING divided graph with avg and individual lines -->
                                <div class="row ui raised segment">
                                    <p class="ui ribbon label large blue">How other users' mood relate to yours:</p>
                                     <%= line_chart [
                                      {name: "All users", data: Post.group_by_week(:created_at).average(:affect)},
                                      {name: "Your data", data: current_user.posts.group_by_week(:created_at).average(:affect)}
                                    ], {
                                        colors: ['#696969', '#1111cc'],
                                        series: {
                                            0 => {lineWidth: 1},
                                            1 => {lineWidth: 2},
                                        },
                                        xtitle: "Time",
                                        ytitle: "Affect"
                                    }  %>
                                </div>
                            <% else %>
                                <div class="row ui raised segment">
                                    <p class="ui ribbon labelui ribbon label large blue">How your physical activity mood changes over time:</p>
                                    <%= line_chart current_user.posts.pluck("created_at, affect"),xmin:"2020-01-01", xmax: "2021-01-01", colors: ["#f77e6e"] %>
                                </div>
                                <br>
                            <% end %>
                            <!-- chart entertainment for posts -->
                            <% if current_user.condition == 1 %>
                                    <!-- here -->

                                <!-- option 1: ugly overlaid graph with library settings -->
                                <%#= line_chart [
                                  {name: "All users", data: Post.pluck("created_at, entertainment")},
                                  {name: "Your data", data: current_user.posts.pluck("created_at, entertainment")}
                                ], library:  lib_set_entertainment %>
                                <!-- end of ugly overlaid graph with library settings -->

                                <!-- option 2: WORKING divided graph with avg and individual lines -->
                                <div class="row ui raised  segment">
                                    <p class="ui ribbon label large blue">How other users' experiences relate to yours :</p>
                                    <%= line_chart [
                                      {name: "All users", data: Post.group_by_week(:created_at).average(:entertainment)},
                                      {name: "Your data", data: current_user.posts.group_by_week(:created_at).average(:entertainment)}
                                    ],
                                        colors: ['#696969', '#3366cc'],
                                        series: {
                                            0 => {lineWidth: 1},
                                            1 => {lineWidth: 2},
                                        },
                                        xtitle: "Time",
                                        ytitle: "Entertainment"
                                     %>
                                </div>
                                <!-- end of divided graph with avg and individual lines -->

                                <!-- option 3-- multi line graph -->
                                <div class="row ui raised  segment">
                                    <p class="ui ribbon label large blue">How other users' experiences relate to yours :</p>

                                    <!-- collecteing usrs with posts and showing up to 5 -->
                                    <% userswithposts = []; 
                                        User.all.each do |user|
                                         if user.posts.count != 0
                                             userswithposts.push user
                                         end
                                        end %>
                                     <%= line_chart userswithposts.sample(6).map { |user|
                                        {name: user.username, data: user.posts.group_by_week(:created_at).average(:entertainment)}
                                    }%>

                                     <!-- UNDER CONSTRUCTION styling pending-->

                                </div>
                                <!-- end of multi line graph -->
                            <% else %>
                                <div class="row ui raised segment">
                                    <p class="ui ribbon label large blue">How your physical activity experiences change over time:</p>
                                    <%= line_chart current_user.posts.pluck("created_at, entertainment"),xmin:"2020-01-01", xmax: "2021-01-01", colors: ["#2CA"] %>
                                </div>
                                <br>
                            <% end %>

                            <!-- coffee and water feedback charts -->
                            <div class="row ui raised segment">
                                    <div class="col">
                                        <!-- chart for coffee -->
                                            <p class="h5 center">Coffee cups per day:</p>
                                            <%= column_chart current_user.coffees.group_by_day_of_week(:created_at, format: "%a",range: DateTime.now.at_beginning_of_week..DateTime.now).count, colors: ["#CC8566"], height: "300px",width:"450px", min: 0, max: current_user.climit %>
                                    </div>
                                    <div class="col">
                                            <!-- chart for water -->
                                            <p class="h5 center ">Water cups per day:</p>
                                            <%= column_chart current_user.waters.group_by_day_of_week(:created_at, format: "%a",range: DateTime.now.at_beginning_of_week..DateTime.now).count, colors: ["#87b4f8"], height: "300px",width:"450px", min: 0, max: current_user.wlimit %>
                                    </div>
                            </div>
                            <!-- end of coffee and water feedback charts -->


                        <% else %>
                           <!-- not logged in view -->
                            <div style="margin-top: 20px;margin-bottom: 20px; " class="not-logged">
                                <div class="row justify-content-center">
                                    <div class="profile-userbuttons" style="margin-right: 20px;">
                                        <a href="<%= new_user_registration_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN UP </button></a>
                                    </div>
                                    <div class="profile-userbuttons">
                                        <a href="<%= new_user_session_path %>"><button type="button" class="btn btn-success btn-lg"> SIGN IN </button></a>
                                    </div>
                                </div>
                            </div>
                            <!-- not logged in view -->
                        <% end %>
                    </div>
                </div>
			</div>
</div>